Tweak script implementations for my improved coding skills and taste

diff --git a/sys-setup/set-osx-hostname b/sys-setup/set-osx-hostname
--- a/sys-setup/set-osx-hostname
+++ b/sys-setup/set-osx-hostname
@@ -1,5 +1,6 @@
 #!/bin/bash
-# set-osx-hostname
+#
+# set-osx-hostname - Set the system hostname on macOS.
 #
 # sudo set-osx-hostname <name>
 #
@@ -7,13 +8,13 @@
 # This is intended to be the equivalent of manually setting it in the
 # System Preferences > Sharing control panel.
 #
-# I'm not sure if it actually works
+# I'm not sure if this actually works.
 
 PROGRAM_NAME="$(basename $0)"
 
 function usage() {
   cat <<EOF
-$PROGRAM_NAME - set the hostname on this machine
+$PROGRAM_NAME - Set the hostname on this macOS machine.
 
 Usage:
   $PROGRAM_NAME [-x] <hostname>
@@ -35,7 +36,7 @@ while getopts xh opt; do
       exit 0
       ;;
     \?)
-      echo >&2 "See '$PROGRAM_NAME -h' for usage"
+      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."
       exit 1
       ;;
   esac
@@ -63,3 +64,4 @@ if [[ $OPT_TRACE == 1 ]]; then
 fi
 
 main
+exit 0
diff --git a/sys-setup/setup-osx-homebrew b/sys-setup/setup-osx-homebrew
--- a/sys-setup/setup-osx-homebrew
+++ b/sys-setup/setup-osx-homebrew
@@ -2,9 +2,13 @@
 #
 # Sets up Homebrew on this machine.
 #
-# This is idempotent, so you can rerun it on a machine that already has brew installed,
-# though you may see (lots of) spurious warning messages. Each run does git fetches, so
-# it requires a network connection even if everything is already set up.
+# THIS IS OUTDATED. Homebrew has changed their default installation location, setup
+# process, and the whole Cask mechanism in the last few years (as of 2022). This script
+# has not been updated for that uet.
+#
+# This script is (hopefully) idempotent, so you can rerun it on a machine that already
+# has brew installed, though you may see (lots of) spurious warning messages. Each run
+# does git fetches, so it requires a network connection even if everything is already set up.
 
 set -e
 
@@ -12,7 +16,7 @@ PROGRAM_NAME="$(basename $0)"
 
 function usage() {
   cat <<EOF
-$PROGRAM_NAME - set up Homebrew and some formulae on this machine
+$PROGRAM_NAME - Set up Homebrew and some formulae on this machine.
 
 Usage:
   $PROGRAM_NAME [-x]
@@ -39,7 +43,7 @@ while getopts xh opt; do
       exit 0
       ;;
     \?)
-      echo >&2 "See '$PROGRAM_NAME -h' for usage"
+      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."
       exit 1
       ;;
   esac
@@ -60,7 +64,7 @@ function ensure_github_user_fork_remote() {
 
 function main() {
 
-THISDIR="$( dirname "${BASH_SOURCE[0]}" )"
+THISDIR=$(dirname "${BASH_SOURCE[0]}")
 GITHUB_USERNAME=apjanke
 my_brew_cfg_dir="$THISDIR/homebrew"
 
@@ -69,9 +73,10 @@ my_brew_cfg_dir="$THISDIR/homebrew"
 # Check for Xcode or CLT
 if ! xcode-select -p >/dev/null; then
   cat >&2 <<EOF
-Error: Neither Xcode nor CLT are installed. Please install one.
-  To install CLT:  sudo xcode-select --install
-  To do Xcode:     Install Xcode and then run:
+ERROR: Neither Xcode nor Xcode CLT are installed. Please install one.
+
+  To install Scode CLT:  sudo xcode-select --install
+  To do Xcode:           Install Xcode and then run:
      sudo xcode-select -s /Applications/Xcode-<version>.app
 EOF
   exit 1
@@ -79,29 +84,29 @@ fi
 
 # Install Homebrew
 (
-if [[ -z $(which brew) ]]; then
-  INSTALLER_URL=https://raw.githubusercontent.com/Homebrew/install/master/install
-  ruby -e "$(curl -fsSL $INSTALLER_URL)"
-else
-  echo "Homebrew is already installed."
-fi
-cd $(brew --repo)
-if [[ -e .git/shallow ]]; then
-  git fetch --unshallow
-fi
-ensure_github_user_fork_remote $GITHUB_USERNAME brew
-git fetch --all
-cd "$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core"
-if [[ -e .git/shallow ]]; then
-  git fetch --unshallow
-fi
-ensure_github_user_fork_remote $GITHUB_USERNAME homebrew-core
-git fetch --all
+  if [[ -z $(which brew) ]]; then
+    INSTALLER_URL=https://raw.githubusercontent.com/Homebrew/install/master/install
+    ruby -e "$(curl -fsSL $INSTALLER_URL)"
+  else
+    echo "Homebrew is already installed."
+  fi
+  cd $(brew --repo)
+  if [[ -e .git/shallow ]]; then
+    git fetch --unshallow
+  fi
+  ensure_github_user_fork_remote $GITHUB_USERNAME brew
+  git fetch --all
+  cd "$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core"
+  if [[ -e .git/shallow ]]; then
+    git fetch --unshallow
+  fi
+  ensure_github_user_fork_remote $GITHUB_USERNAME homebrew-core
+  git fetch --all
 )
 
 # Pick what to install
 if [[ -e "$my_brew_cfg_dir" ]]; then
-  echo "Found brew config dir at $my_brew_cfg_dir"
+  echo "Found brew config dir at: $my_brew_cfg_dir"
   taps=($(cat "$my_brew_cfg_dir/brew-taps-standard"))
   formulae=($(cat "$my_brew_cfg_dir/brew-formulae-standard"))
   casks=($(cat "$my_brew_cfg_dir/brew-casks-standard"))
@@ -109,7 +114,7 @@ if [[ -e "$my_brew_cfg_dir" ]]; then
       casks=()
   fi
 else
-  echo "No brew config dir found at '$my_brew_cfg_dir'; Using defaults"
+  echo "No brew config dir found at '$my_brew_cfg_dir'; using defaults."
   # Common defaults
   taps=( apjanke/personal )
   formulae=( bash zsh browser duti wget dos2unix fortune git pstree tree watch )
@@ -139,4 +144,4 @@ _do brew install "${formulae[@]}"
 }
 
 main
-
+exit 0
diff --git a/sys-setup/setup-osx-macports b/sys-setup/setup-osx-macports
--- a/sys-setup/setup-osx-macports
+++ b/sys-setup/setup-osx-macports
@@ -2,8 +2,8 @@
 #
 # Sets up MacPorts-based stuff on this machine.
 #
-# This assumes you already have MacPorts installed. It just installs my preferred packages
-# under MacPorts.
+# This assumes you already have MacPorts installed. It just installs apjanke's
+# preferred packages using MacPorts.
 
 set -e
 
@@ -11,7 +11,7 @@ PROGRAM_NAME="$(basename $0)"
 
 function usage() {
   cat <<EOF
-$PROGRAM_NAME - Install my preferred MacPorts packages on this machine
+$PROGRAM_NAME - Install apjanke's preferred MacPorts packages on this machine
 
 Usage:
   $PROGRAM_NAME [-x]
@@ -33,7 +33,7 @@ while getopts xh opt; do
       exit 0
       ;;
     \?)
-      echo >&2 "See '$PROGRAM_NAME -h' for usage"
+      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage"
       exit 1
       ;;
   esac
@@ -45,14 +45,13 @@ function _do() {
 }
 
 function main() {
-
   THISDIR="$( dirname "${BASH_SOURCE[0]}" )"
   my_macports_cfg_dir="$THISDIR/macports"
   ports=($(cat "$my_macports_cfg_dir/macports-ports-standard"))
 
   sudo port selfupdate
   sudo port -N install "${ports[@]}"
-
 }
 
 main
+exit 0
diff --git a/sys-setup/setup-osx-system b/sys-setup/setup-osx-system
--- a/sys-setup/setup-osx-system
+++ b/sys-setup/setup-osx-system
@@ -13,7 +13,7 @@ PROGRAM_NAME="$(basename $0)"
 
 function usage() {
   cat <<EOF
-$PROGRAM_NAME - set up system settings to apjanke's preferred ones
+$PROGRAM_NAME - Set up system settings according to apjanke's preferences
 
 Usage:
   $PROGRAM_NAME [-x]
@@ -35,7 +35,7 @@ while getopts xh opt; do
       exit 0
       ;;
     \?)
-      echo >&2 "See '$PROGRAM_NAME -h' for usage"
+      echo >&2 "ERROR: Invalid option. See '$PROGRAM_NAME -h' for usage."
       exit 1
       ;;
   esac
@@ -43,7 +43,7 @@ done
 
 function main() {
 
-# Ask for administrator password up front
+# Prompt for administrator password up front
 sudo -v
 
 ################################################
@@ -64,13 +64,15 @@ if false; then
   elif [[ $rslt == *"already installed"* ]]; then
     echo "Looks like Xcode CLT is already installed."
   else
-    echo "Error installing Xcode CLT: $rslt"
+    echo "ERROR: Failed installing Xcode CLT: $rslt"
     exit 1
   fi
 fi
 
 # Only /usr/local exists by default
 # I might want to link in some binaries, so make sure bin/ exists, too
+
+# TODO: These are outdated now that Homebrew has changed its installation location.
 
 # These sudos aren't necessary or desirable if Homebrew is being installed.
 # But I'm not going to assume that yet.
@@ -82,13 +84,12 @@ fi
 
 # Link Sublime Text command line tool
 if [[ -e /usr/local/bin/subl ]]; then
-  echo "subl is already linked"
+  echo "subl is already linked."
 else
-  # Prefer Sublime version 2 since 3 is still in beta
-  if [[ -e "/Applications/Sublime Text 2.app" ]]; then
-    sudo ln -s -v "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
-  elif [[ -e "/Applications/Sublime Text 3.app" ]]; then
+  if [[ -e "/Applications/Sublime Text 3.app" ]]; then
     sudo ln -s -v "/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
+  elif [[ -e "/Applications/Sublime Text 2.app" ]]; then
+    sudo ln -s -v "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
   fi
 fi
 
@@ -158,4 +159,5 @@ if [[ $OPT_TRACE == 1 ]]; then
   set -x
 fi
 
-main; exit 0
+main
+exit 0
diff --git a/sys-setup/setup-osx-user b/sys-setup/setup-osx-user
--- a/sys-setup/setup-osx-user
+++ b/sys-setup/setup-osx-user
@@ -29,7 +29,7 @@ PROGRAM_NAME="$(basename $0)"
 
 function usage() {
   cat <<EOF
-$PROGRAM_NAME - set up system settings to apjanke's preferred ones
+$PROGRAM_NAME - Set up system settings according to apjanke's preferences
 
 Usage:
   $PROGRAM_NAME [-x] [-v] [-k]
@@ -108,7 +108,7 @@ function defaults-write() {
   #echo "current is '$current', want '$value'"
   # booleans are written as true/false, but read back as 1/0
   local expected
-  if [[ $value_type == bool ]]; then
+  if [[ "$value_type" == bool ]]; then
     if [[ "$value" == true ]]; then
       expected=1
     else
@@ -133,7 +133,7 @@ function defaults-delete() {
   local key="$2"
   if defaults read "$domain" "$key" &>/dev/null; then
     defaults delete "$domain" "$key"
-    v_echo "deleted defaults $domain $key"
+    v_echo "Deleted defaults $domain $key"
     changed-something
   else
     v_echo "defaults $domain $key is already deleted"
@@ -603,13 +603,13 @@ CHANGED=0
 function update_iterm_prefs() {
 local ITERM_PREFS_DIR="$DOTFILES_REPO_PATH/iTerm2/$ITERM_PREFERENCES_SET"
 if [[ ! -d "$ITERM_PREFS_DIR" ]]; then
-  echo >&2 "Warning: Not updating iTerm2 shared prefs dir because dir does not exist: '$ITERM_PREFS_DIR'"
+  echo >&2 "WARNING: Not updating iTerm2 shared prefs dir because dir does not exist: '$ITERM_PREFS_DIR'"
   return
 fi
 if ps aux | grep '[i]Term' &>/dev/null; then
   if [[ $(defaults read com.googlecode.iterm2 PrefsCustomFolder) != "$ITERM_PREFS_DIR" ]]; then
-    echo >&2 "Warning: Cannot change iTerm2 preferences shared folder while iTerm2 is running"
-    echo >&2 "Warning: iTerm2 preferences folder not updated"
+    echo >&2 "WARNING: Cannot change iTerm2 preferences shared folder while iTerm2 is running."
+    echo >&2 "WARNING: iTerm2 preferences folder was not updated."
   fi
 else
   defaults-write com.googlecode.iterm2 PrefsCustomFolder "$ITERM_PREFS_DIR"
@@ -818,7 +818,10 @@ defaults-write org.herf.Flux wakeTime -int 600
 mkdir -p ~/local/RubymineProjects
 if [[ ! -e "~/local/RubymineProjects/Homebrew-local" ]]; then
   if [[ -e "$MANUAL_SETTINGS_PATH/Rubymine/rubymine-homebrew-local.tgz" ]]; then
-    ( cd ~/local/RubymineProjects; tar xf "$MANUAL_SETTINGS_PATH/Rubymine/rubymine-homebrew-local.tgz")
+    (
+      cd ~/local/RubymineProjects
+      tar xf "$MANUAL_SETTINGS_PATH/Rubymine/rubymine-homebrew-local.tgz"
+    )
   fi
 fi
 
@@ -832,7 +835,13 @@ $MYDIR/src/setup-oh-my-zsh
 # Prezto
 ################################################
 
-ln -s $HOME/Dropbox/#repos/prezto $HOME/.zprezto
+if [[ -d "$HOME/Dropbox/#repos/prezto" ]]; then
+  ln -s "$HOME/Dropbox/#repos/prezto" "$HOME/.zprezto"
+elif [[ -d "$HOME/repos/prezto" ]]; then
+  ln -s "$HOME/repos/prezto" "$HOME/.zprezto"
+else
+  echo "No prezto repo found; not linking to ~/.zprezto."
+fi
 
 ################################################
 # File associations
@@ -843,14 +852,14 @@ if which duti >/dev/null; then
     duti -s com.barebones.bbedit .txt all
   fi
 else
-  echo "duti is not installed. Not setting file associations."
+  echo "WARNING: duti is not installed. Not setting file associations."
 fi
 
 ################################################
 # My conventional directories
 ################################################
 
-mkdir -p ~/local/repos
+mkdir -p ~/local
 mkdir -p ~/local/opp
 mkdir -p ~/local/RubymineProjects
 
@@ -861,12 +870,10 @@ mkdir -p ~/local/RubymineProjects
 # User settings for when running as a guest inside a VM
 
 if pkgutil --pkg-info com.vmware.tools.macos.pkg.files &>/dev/null; then
-
   # Re-enable “natural” (Lion-style) scrolling
   # This will end up having old-style scrolling in effect, because of interaction
   # with the host's scrolling setup and/or the VM's mouse driver
   defaults-write NSGlobalDomain com.apple.swipescrolldirection -bool true
-
 fi
 
 ################################################
@@ -892,4 +899,5 @@ if [[ $OPT_TRACE == 1 ]]; then
   set -x
 fi
 
-main; exit 0
+main
+exit 0
