some shellcheck and style fixes in sys-setup

diff --git a/sys-setup/set-macos-hostname b/sys-setup/set-macos-hostname
--- a/sys-setup/set-macos-hostname
+++ b/sys-setup/set-macos-hostname
@@ -10,7 +10,7 @@
 #
 # I'm not sure if this actually works.
 
-PROGRAM_NAME="$(basename $0)"
+PROGRAM_NAME="$(basename "$0")"
 
 function usage() {
   cat <<EOF
@@ -26,27 +26,6 @@ Options:
 EOF
 }
 
-while getopts xh opt; do
-  case $opt in
-    x)
-      OPT_TRACE=1
-      ;;
-    h)
-      usage
-      exit 0
-      ;;
-    \?)
-      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."
-      exit 1
-      ;;
-  esac
-done
-
-if [[ -z "$1" ]]; then
-  usage
-  exit 1
-fi
-
 function set-osx-hostname() {
   name="$1"
   sudo scutil --set ComputerName "$name"
@@ -56,12 +35,21 @@ function set-osx-hostname() {
 }
 
 function main() {
+  while getopts xh opt; do
+    case $opt in
+      x)   OPT_TRACE=1 ;;
+      h)   usage; exit 0 ;;
+      \?)  echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."; exit 1 ;;
+    esac
+  done
+  if [[ $OPT_TRACE = 1 ]]; then set -o xtrace; fi
+
+  if [[ -z "$1" ]]; then
+    usage; exit 1
+  fi
+
   set-osx-hostname "$1"
 }
 
-if [[ $OPT_TRACE == 1 ]]; then
-  set -x
-fi
-
-main
+main "$@"
 exit 0
diff --git a/sys-setup/setup-macos-homebrew b/sys-setup/setup-macos-homebrew
--- a/sys-setup/setup-macos-homebrew
+++ b/sys-setup/setup-macos-homebrew
@@ -13,7 +13,7 @@
 
 set -e
 
-PROGRAM_NAME="$(basename $0)"
+PROGRAM_NAME="$(basename "$0")"
 
 function usage() {
   cat <<EOF
@@ -33,20 +33,10 @@ EOF
 
 while getopts xh opt; do
   case $opt in
-    x)
-      OPT_TRACE=1
-      ;;
-    n)
-      NO_CASKS=1
-      ;;
-    h)
-      usage
-      exit 0
-      ;;
-    \?)
-      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."
-      exit 1
-      ;;
+    x)   OPT_TRACE=1 ;;
+    n)   NO_CASKS=1 ;;
+    h)   usage; exit 0 ;;
+    \?)  echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage."; exit 1 ;;
   esac
 done
 
@@ -55,15 +45,16 @@ function _do() {
   "$@"
 }
 
+# shellcheck disable=SC2329
 function ensure_github_user_fork_remote() {
-  local USERNAME="$1"
-  local REPO="$2"
-  if ! git remote get-url "$USERNAME" &>/dev/null; then
-    _do git remote add "$USERNAME" "https://github.com/${USERNAME}/${REPO}.git"
+  local username="$1" repo="$2"
+  if ! git remote get-url "$username" &>/dev/null; then
+    _do git remote add "$username" "https://github.com/${username}/${repo}.git"
   fi
 }
 
 function main() {
+if [[ $OPT_TRACE = 1 ]]; then set -o xtrace; fi
 
 THISDIR=$(dirname "${BASH_SOURCE[0]}")
 GITHUB_USERNAME=apjanke
@@ -125,7 +116,7 @@ done
 
 # Do casks first so Java gets picked up; it is a dependency of some formulae
 for cask in "${casks[@]}"; do
-  _do brew install --cask $cask
+  _do brew install --cask "$cask"
 done
 
 _do brew install "${formulae[@]}"
diff --git a/sys-setup/setup-macos-macports b/sys-setup/setup-macos-macports
--- a/sys-setup/setup-macos-macports
+++ b/sys-setup/setup-macos-macports
@@ -7,7 +7,7 @@
 
 set -e
 
-PROGRAM_NAME="$(basename $0)"
+PROGRAM_NAME="$(basename "$0")"
 
 function usage() {
   cat <<EOF
@@ -25,26 +25,21 @@ EOF
 
 while getopts xh opt; do
   case $opt in
-    x)
-      OPT_TRACE=1
-      ;;
-    h)
-      usage
-      exit 0
-      ;;
-    \?)
-      echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage"
-      exit 1
-      ;;
+    x)   OPT_TRACE=1 ;;
+    h)   usage; exit 0 ;;
+    \?)  echo >&2 "ERROR: Invalid argument. See '$PROGRAM_NAME -h' for usage"; exit 1 ;;
   esac
 done
 
+# shellcheck disable=SC2329
 function _do() {
   echo "$@"
   "$@"
 }
 
 function main() {
+  if [[ $OPT_TRACE = 1 ]]; then set -o xtrace; fi
+
   THISDIR="$( dirname "${BASH_SOURCE[0]}" )"
   my_macports_cfg_dir="$THISDIR/macports"
   ports=($(cat "$my_macports_cfg_dir/macports-ports-standard"))
