sys-setup: re-enable Documents in Spotlight search

diff --git a/sys-setup/setup-osx-user b/sys-setup/setup-osx-user
--- a/sys-setup/setup-osx-user
+++ b/sys-setup/setup-osx-user
@@ -5,54 +5,37 @@
 # This script is idempotent, so it can be run repeatedly on the same machine
 # and account.
 #
+# Options:
+#    -v    verbose output
+#    -k    kill all affected apps
+#
 # The coding style has a lot of copy-and-paste instead of being factored in to
 # functions. This is intentional, to allow easy interactive copy-and-pasting of
 # individual commands to the terminal. A "defaults-write" call may be replaced with
 # "defaults write" at the command line.
+
 
 MYDIR="$( dirname "${BASH_SOURCE[0]}" )"
 DROPBOX="$HOME/Dropbox"
 SERIALS_DIR="$DROPBOX/records/licenses and serials"
 WALLPAPER_FILE="/Library/Desktop Pictures/Wave.jpg"
 
-PROGRAM_NAME="$(basename $0)"
-
-function usage() {
-  cat <<EOF
-$PROGRAM_NAME - set up user settings to apjanke's preferred ones
-
-Usage: 
-  $PROGRAM_NAME [-v] [-k] [-x] [-h]
-
-Options:
-    -v    verbose output
-    -k    kill all affected apps
-    -x    trace program execution
-    -h    display help
-EOF
-}
-
-while getopts vkxh opt; do
+while getopts vk opt; do
   case $opt in
     v)
       VERBOSE=1
       ;;
     k)
-      OPT_KILL=1
-      ;;
-    x)
-      OPT_TRACE=1
-      ;;
-    h)
-      usage
-      exit 0
+      DO_KILL=1
       ;;
     \?)
-      echo >&2 "See '$PROGRAM_NAME -h' for usage"
+      echo >&2 "Invalid option: -$OPTARG"
       exit 1
       ;;
   esac
 done
+
+OSX_VERSION=$(sw_vers -productVersion)
 
 function CFPreferencesAppSynchronize() {
   python - <<END
@@ -102,10 +85,10 @@ function defaults-write() {
   fi
   # This changed-value check is not perfect; it gets false positives for complex types
   if [[ "$current" == "$expected" ]]; then
-    v_echo "defaults $domain $key is already set: $current"
+    v_echo "defaults-write: $domain $key is already set: $current"
   else
     defaults write "$domain" "$key" "$@"
-    v_echo "wrote defaults $domain $key: $value"
+    v_echo "defaults-write: wrote defaults $domain $key: $value"
     changed-something
   fi
 }
@@ -122,11 +105,6 @@ function defaults-delete() {
     v_echo "defaults $domain $key is already deleted"
   fi
 }
-
-
-function main() {
-
-OSX_VERSION=$(sw_vers -productVersion)
 
 ################################################
 # Dock
@@ -146,7 +124,7 @@ defaults-write com.apple.dock tilesize -float 32
 # Autohide dock
 defaults-write com.apple.dock autohide -bool true
 # Auto-hiding delay
-# Remove the auto-hiding Dock delay
+# (I prefer a bit of delay, so I'm leaving it in)
 #defaults-write com.apple.dock autohide-delay -float 0
 defaults-delete com.apple.dock autohide-delay
 # Remove the animation when hiding/showing the Dock
@@ -205,7 +183,7 @@ for app in "${unwanted_apps[@]}"; do
 done
 
 if [[ $CHANGED == 1 ]]; then
-  killall dock
+  killall dock 2>/dev/null
 fi
 
 ################################################
@@ -467,12 +445,12 @@ spotlight_items=(
   '{"enabled" = 1;"name" = "EVENT_TODO";}'
   '{"enabled" = 1;"name" = "IMAGES";}'
   '{"enabled" = 1;"name" = "MESSAGES";}'
+  '{"enabled" = 1;"name" = "DOCUMENTS";}'
+  '{"enabled" = 1;"name" = "BOOKMARKS";}'
+  '{"enabled" = 1;"name" = "PRESENTATIONS";}'
   '{"enabled" = 0;"name" = "FONTS";}'
-  '{"enabled" = 0;"name" = "DOCUMENTS";}'
-  '{"enabled" = 0;"name" = "BOOKMARKS";}'
   '{"enabled" = 0;"name" = "MUSIC";}'
   '{"enabled" = 0;"name" = "MOVIES";}'
-  '{"enabled" = 0;"name" = "PRESENTATIONS";}'
   '{"enabled" = 0;"name" = "SPREADSHEETS";}'
   '{"enabled" = 0;"name" = "SOURCE";}'
   )
@@ -487,6 +465,7 @@ if [[ $OSX_VERSION == 10.1* ]]; then
   '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
   )
 fi
+#TODO: force reindexing if item set was changed
 defaults-write com.apple.spotlight orderedItems -array "${spotlight_items[@]}"
 
 ################################################
@@ -758,7 +737,7 @@ fi
 # Kill affected applications
 ################################################
 
-if [[ $OPT_KILL == 1 ]]; then
+if [[ $DO_KILL == 1 ]]; then
   for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
       "Dock" "Finder" "Google Chrome" "Google Chrome Canary" "Mail" "Messages" \
       "Opera" "Safari" "SizeUp" "Spectacle" "SystemUIServer" \
@@ -769,10 +748,3 @@ fi
 
 echo "Done. Note that some of these changes require a logout/restart to take effect."
 
-}
-
-if [[ $OPT_TRACE == 1 ]]; then
-  set -x
-fi
-
-main
