Add JDK casks

diff --git a/sys-setup/setup-osx-homebrew b/sys-setup/setup-osx-homebrew
--- a/sys-setup/setup-osx-homebrew
+++ b/sys-setup/setup-osx-homebrew
@@ -77,10 +77,12 @@ EOF
   exit 1
 fi
 # Check for JDK
-if ! pkgutil --pkgs | grep com.oracle.jdk >/dev/null; then
-  echo >&2 "Error: Java JDK is not installed. Please install it."
-  exit 1
-fi
+# Require this because I don't trust brew cask to install it (yet)
+# In progress: I'm trying out casks now. If this works, then this section can be removed
+#if ! pkgutil --pkgs | grep com.oracle.jdk >/dev/null; then
+#  echo >&2 "Error: Java JDK is not installed. Please install it."
+#  exit 1
+#fi
 
 # Install Homebrew
 (
